[package]
name = "UntitledMappingProject"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "db_manager"
path = "src/db_manager.rs"

[dependencies]
mysql = "*"